# Generated by Django 6.0.3 on 2026-04-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('menu', 'Menú del Día'), ('extra', 'Plato Extra')], max_length=10)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
