# Generated by Django 6.0.3 on 2026-04-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_menu_to_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Carta del dia',
                'verbose_name_plural': 'Cartas del dia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cartadia')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.plato')),
            ],
            options={
                'unique_together': {('carta', 'plato')},
            },
        ),
    ]
